### PR TITLE
Move SpooledTemporaryFile.newlines from delegation to property

### PR DESCRIPTION
**Pull request by cake-monotone**
Hi!

I found a minor issue in SpooledTemporaryFile and I fixed it.

Fix https://github.com/Tinche/aiofiles/issues/118

ref) https://github.com/python/cpython/blob/3e43fac2503afe219336742b150b3ef6e470686f/Lib/tempfile.py#L747

### CODE REVIEW

**Comment by Tinche** [comment]
Thanks! Does this have a test somewhere?

**Comment by cake-monotone** [comment]
You're right :+1: I missed it.

Here's the missed test.

**Comment by cake-monotone** [comment]
hmm... it's weird

python3.6 's tempfile.SpooledTemporaryFile.newlines has diffrent implementation. ([code](https://github.com/python/cpython/blob/b74b1f36993a4e1700869133f3be13dd60ef4e40/Lib/tempfile.py))

it's effected by tempfile.SpooledTemporaryFile.\_\_init__(newline)

**Comment by cake-monotone** [comment]
Because of other works, I think I'll be able to fix CI-fail tomorrow.

**Comment by cake-monotone** [comment]
Now, the test will be skipped if `sys.version_info <= (3, 6)`

Text-mode `tempfile.SpooledTemporaryFile` use `StringIO` in py3.6. (https://github.com/python/cpython/blob/v3.6.15/Lib/tempfile.py#L647)
and `StringIO` doesn't implement `newlines`.

I think it's okay to skip py3.6

**Comment by Tinche** [comment]
Thanks!

**Pull request merged**
