### PR TITLE
Add function: aiofiles.os.access()

### PR DESCRIPTION
**Pull request by rexzhang**
issue # 145

### CODE REVIEW

**Comment by rexzhang** [comment]
Please wait some time, I will add more unit test

**Comment by rexzhang** [comment]
finished

**Comment by Tinche** [comment]
Add a changelog fragment too please (create a new section for 22.2.0 if it's not there).

**Comment by rexzhang** [comment]
> Add a changelog fragment too please (create a new section for 22.2.0 if it's not there).

done

**Comment by Tinche** [comment]
Thanks! The failing test is a pip bug, so I'm going to merge this in.

**Pull request merged**
