### PR TITLE
Python3.8 support

### PR DESCRIPTION
**Pull request by kasheemlew**

### CODE REVIEW

**Comment by elonen** [comment]
3.8 support should also include suppressing deprecation warning on @coroutine, as in:
https://github.com/Qiskit/qiskit-ibmq-provider/pull/498/files

(Python3.8 deprecated "@coroutine" and "yield from" in favor of "async def" and "await func".)

**Comment by PikalaxALT** [comment]
Should also replace `yield from` with `await`, and get rid of the `@asyncio.coroutine` decorators so as to phase out support for Python 3.4.

**Comment by kasheemlew** [comment]
hi, @PikalaxALT . Should I replace `yield from` and `@asyncio.coroutine` in this pr or create another one?

**Comment by gyermolenko** [comment]
related #54

**Comment by blueyed** [comment]
> hi, @PikalaxALT . Should I replace `yield from` and `@asyncio.coroutine` in this pr or create another one? I think suppressing warnings is enough for guys using Python3.8

IMHO it should not filter them (and if so just in a more central place), but fix them.

I've started doing so, then looked for existing PRs, and noticed that this library appears to be unmaintained currently anyway.

As for this PR I'd say it's good to add the trove classifier (1st commit), and fix the deprecation warnings separately.

**Comment by Tinche** [comment]
Hi,

thanks for your trouble, I did this myself by modernizing the code base.

**Pull request closed without merging**
