### PR TITLE
Add async zipfiles module

### PR DESCRIPTION
**Pull request by xsduan**
Hello, I have recently run into the need for async zipfiles, so I made my own module. I hope you'll find this useful enough to include.

I have also made `_open` public, renamed it to `run_threadpool`, and made it more generic, because it reduces the amount of copying and pasting I needed for this module. I know this is a relatively big change, so if you would rather not I can just revert it to not touch that area, since I have it in that format as well.

also, it's sort of unclear whether or not we should be using async/await or `@asyncio.coroutine`, because some tests with `async with` use it but most everything else uses the decorator.

### CODE REVIEW

**Comment by NotoriousRebel** [comment]
Any updates to this?

**Comment by untereiner** [comment]
Hi @Tinche, are you interested to add Zipfile ? I would be in the need too

**Comment by jmkd3v** [comment]
I also would like to see this implemented.

**Comment by gaby** [comment]
@Tinche friendly bump

**Comment by gaby** [comment]
@Tinche Can you check this PR? Thanks!

**Pull request closed without merging**
