### PR TITLE
Add anyio support

### LINKED ISSUE #96: anyio/trio support
Hello, I think it'd be great to leverage https://anyio.readthedocs.io/ so that code that relies on this package can use asyncio or [trio](https://trio.readthedocs.io) as the async backend.  An example would be starlette, if https://github.com/encode/starlette/pull/1157 is merged.

### PR DESCRIPTION
**Pull request by uSpike**
This would fix #96

Adds support for other async frameworks using `anyio`.  The only thing to wait on is the release of `anyio` version 3, but I'd like to know if there's interest in this!

Cheers.

### CODE REVIEW

**Comment by Tinche** [comment]
I wouldn't mind having this in tbh!

**Comment by uSpike** [comment]
Anyio 3.0 is out, and this PR is rebased and ready for review @Tinche

**Comment by uSpike** [comment]
Of note, I had to increase the minimum python version to 3.6.2 to match anyio requirements.

**Comment by uSpike** [comment]
Actually, upon further inspection some tests are failing after that rebase.  Will investigate.

**Comment by uSpike** [comment]
Frankly, the `loop` keyword argument for various functions should be deprecated or removed.  It was deprecated in python 3.8 and removed in 3.10.

**Comment by uSpike** [comment]
OK, should be good now.  The entirety of `/src/aiofiles/tempfile/__init__.py` was rewritten with correct line-endings.  It was added with Windows style line endings, so I changed it with `dos2unix` to match the other files.

**Comment by Tinche** [comment]
I opened an issue over at https://github.com/agronholm/anyio/issues/266 asking for clarification since I see anyio already has async file IO support.

**Comment by Tinche** [comment]
Looks like anyio has no actual interest in this, so I'm going to pass. Sorry!

**Comment by uSpike** [comment]
@Tinche i'm confused, you were looking to integrate `aiofiles` *into* anyio?  That was not my intention here.  With this PR you could enable users of asyncio and Trio to use `aiofiles`.  Why close it?

**Pull request closed without merging**
