### PR TITLE
Fix typo: aiofiles.ospath.exists

### PR DESCRIPTION
**Pull request by q0w**

### CODE REVIEW

**Comment by Tinche** [comment]
Hm right. I agree we should fix it, but we should also keep the old one for backwards compatibility.

**Comment by q0w** [comment]
Hmm, but 0.7.0 does not have ospath and 0.8.0 is not released.

**Comment by Tinche** [comment]
Oh crap, you're right. Gj!

**Comment by Tinche** [comment]
Can you also fix the test though?

**Comment by q0w** [comment]
Done.

**Comment by Tinche** [comment]
Thanks a lot!

**Pull request merged**
