### PR TITLE
DRY up the os module

### PR DESCRIPTION
**Pull request by cjerdonek**
This will make it easier to address issue #4 and add similar calls, and generally simplify maintenance going forward.

### CODE REVIEW

**Comment by Tinche** [comment]
Hi, sorry for being non-responsive, I've been at a conference. I'll get around to this in a day or two.

**Comment by Tinche** [comment]
LGTM!

**Comment by Tinche** [comment]
Thanks.

**Comment by cjerdonek** [comment]
Thanks!

**Pull request merged**
